services:
  naming-server:
    env_file:
      - .env
    build: ./naming-server
    ports:
      - "8761:8761"
    environment:
      #SPRING_APPLICATION_NAME: naming-server
      #SERVER_PORT: 8761
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: false
      EUREKA_CLIENT_FETCH_REGISTRY: false

  resources-db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_RESOURCES}
    volumes:
      - ./init-scripts/db-resources-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  songs-db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_SONGS}
    volumes:
      - ./init-scripts/db-songs-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  resource-service:
    env_file:
      - .env
    build: ./resource-service
    ports:
      - "8080:8080"
    depends_on:
      - resources-db
      - naming-server

  song-service:
    env_file:
      - .env
    build: ./song-service
    ports:
      - "8082:8082"
    depends_on:
      - songs-db
      - naming-server

