version: "3.9"

services:
  resources-db:
    image: postgres:16-alpine
    env_file:
      - .env.docker
    volumes:
      - ./db-resources-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  songs-db:
    image: postgres:16-alpine
    env_file:
      - .env.docker
    volumes:
      - ./db-songs-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  resource-service:
    env_file:
      - .env.docker
    build: ./resource-service
    ports:
      - "8080:8080"

  song-service:
    env_file:
      - .env.docker
    build: ./song-service
    ports:
      - "8082:8082"

# Related settings for application.properties:
# 
# For resource-service:
# spring.datasource.url=jdbc:postgresql://localhost:5432/resources
# spring.datasource.username=root
# spring.datasource.password=1233
#
# For song-service:
# spring.datasource.url=jdbc:postgresql://localhost:5433/songs
# spring.datasource.username=root
# spring.datasource.password=1233
