version: "3.9"

services:
  resources-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: resources
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1233
    ports:
      - "5432:5432"

  songs-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: songs
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1233
    ports:
      - "5433:5432"

# Related settings for application.properties:
# 
# For resource-service:
# spring.datasource.url=jdbc:postgresql://localhost:5432/resources
# spring.datasource.username=root
# spring.datasource.password=1233
#
# For song-service:
# spring.datasource.url=jdbc:postgresql://localhost:5433/songs
# spring.datasource.username=root
# spring.datasource.password=1233
